# Generated by Django 3.1.2 on 2020-10-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alt',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
