# Generated by Django 3.1.2 on 2020-10-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0002_alt_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alt',
            unique_together={('name', 'realm')},
        ),
    ]
