# Generated by Django 3.1.2 on 2020-10-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0004_auto_20201012_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='alt',
            name='altGender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
            preserve_default=False,
        ),
    ]
