# Generated by Django 3.1.2 on 2020-10-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0005_alt_altgender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alt',
            old_name='level',
            new_name='altLevel',
        ),
        migrations.RenameField(
            model_name='alt',
            old_name='name',
            new_name='altName',
        ),
        migrations.RenameField(
            model_name='alt',
            old_name='realm',
            new_name='altRealm',
        ),
        migrations.AddField(
            model_name='alt',
            name='altFaction',
            field=models.CharField(choices=[('Alliance', 'Alliance'), ('Horde', 'Horde')], default='Alliance', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alt',
            name='altClass',
            field=models.CharField(choices=[('Warrior', 'Warrior'), ('Paladin', 'Paladin'), ('Hunter', 'Hunter'), ('Rogue', 'Rogue'), ('Priest', 'Priest'), ('Shaman', 'Shaman'), ('Mage', 'Mage'), ('Warlock', 'Warlock'), ('Monk', 'Monk'), ('Druid', 'Druid'), ('Demon Hunter', 'Demon Hunter'), ('Death Knight', 'Death Knight')], max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='alt',
            unique_together={('altName', 'altRealm')},
        ),
    ]
