# Generated by Django 3.1.2 on 2020-10-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0006_auto_20201012_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alt',
            name='altRace',
            field=models.CharField(choices=[('Human', 'Human')], max_length=40),
        ),
    ]
