# Generated by Django 3.1.2 on 2020-10-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0010_auto_20201012_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alt',
            name='altRace',
            field=models.CharField(choices=[('Human', 'Human'), ('Orc', 'Orc'), ('Dwarf', 'Dwarf'), ('Night Elf', 'Night Elf'), ('Undead', 'Undead'), ('Tauren', 'Tauren'), ('Gnome', 'Gnome'), ('Troll', 'Troll'), ('Goblin', 'Goblin'), ('Blood Elf', 'Blood Elf'), ('Draenei', 'Draenei'), ('Worgen', 'Worgen'), ('Pandaren', 'Pandaren'), ('Nightbourne', 'Nightbourne'), ('Highmountain Tauren', 'Highmountain Tauren'), ('Void Elf', 'Void Elf'), ('Lightforged Draenei', 'Lightforged Draenei'), ('Zandalari Troll', 'Zandalari Troll'), ('Kul Tiran', 'Kul Tiran'), ('Dark Iron Dwarf', 'Dark Iron Dwarf'), ('Vulpera', 'Vulpera'), ("Mag'ar Orc", 'Maghar Orc'), ('Mechagnome', 'Mechagnome')], max_length=20),
        ),
        migrations.CreateModel(
            name='AltProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altName', models.CharField(max_length=40)),
                ('altRealm', models.CharField(max_length=40)),
                ('professionName', models.CharField(choices=[('Alchemy', 'Alchemy'), ('Blacksmithing', 'Blacksmithing'), ('Enchanting', 'Enchanting'), ('Engineering', 'Engineering'), ('Inscription', 'Inscription'), ('Jewelcrafting', 'Jewelcrafting'), ('Leatherworking', 'Leatherworking'), ('Tailoring', 'Tailoring'), ('Herbalism', 'Herbalism'), ('Mining', 'Mining'), ('Skinning', 'Skinning')], max_length=14)),
            ],
            options={
                'unique_together': {('altName', 'altRealm', 'professionName')},
            },
        ),
    ]
