# Generated by Django 3.1.2 on 2020-10-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0011_auto_20201013_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alt',
            name='id',
        ),
        migrations.AddField(
            model_name='alt',
            name='altId',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
