# Generated by Django 3.1.2 on 2020-10-13 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0012_auto_20201013_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='altprofession',
            name='altId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='wowprof.alt'),
            preserve_default=False,
        ),
    ]
