# Generated by Django 3.1.2 on 2020-11-02 15:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0013_altprofession_altid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltAchievement',
            fields=[
                ('alt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wowprof.alt')),
                ('altAchievementExpiryDate', models.DateTimeField()),
                ('achievementData', models.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name='altprofession',
            old_name='altId',
            new_name='alt',
        ),
        migrations.AddField(
            model_name='alt',
            name='altExpiryDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='altprofession',
            name='altProfessionExpiryDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='altprofession',
            name='professionData',
            field=models.JSONField(default={'test': 'est'}),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='altprofession',
            unique_together={('alt', 'professionName')},
        ),
        migrations.RemoveField(
            model_name='altprofession',
            name='altName',
        ),
        migrations.RemoveField(
            model_name='altprofession',
            name='altRealm',
        ),
    ]
