# Generated by Django 3.1.2 on 2020-11-04 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0014_auto_20201102_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltQuestCompleted',
            fields=[
                ('alt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wowprof.alt')),
                ('AltQuestCompletedExpiryDate', models.DateTimeField()),
                ('questCompletedData', models.JSONField()),
            ],
        ),
    ]
