# Generated by Django 3.1.2 on 2020-11-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0016_auto_20201104_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requiem',
            fields=[
                ('reqId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('reqLevel', models.PositiveSmallIntegerField()),
                ('reqName', models.CharField(max_length=40)),
                ('reqRealm', models.CharField(max_length=40)),
                ('reqClass', models.CharField(choices=[('Warrior', 'Warrior'), ('Paladin', 'Paladin'), ('Hunter', 'Hunter'), ('Rogue', 'Rogue'), ('Priest', 'Priest'), ('Shaman', 'Shaman'), ('Mage', 'Mage'), ('Warlock', 'Warlock'), ('Monk', 'Monk'), ('Druid', 'Druid'), ('Demon Hunter', 'Demon Hunter'), ('Death Knight', 'Death Knight')], max_length=12)),
                ('reqRank', models.PositiveSmallIntegerField()),
                ('reqExpiryDate', models.DateTimeField()),
            ],
            options={
                'unique_together': {('reqName', 'reqRealm')},
            },
        ),
    ]
