# Generated by Django 3.1.2 on 2020-11-19 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0017_requiem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requiem',
            unique_together=set(),
        ),
    ]
