# Generated by Django 3.1.2 on 2020-11-20 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0018_auto_20201119_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requiem',
            name='reqClass',
        ),
        migrations.RemoveField(
            model_name='requiem',
            name='reqId',
        ),
        migrations.RemoveField(
            model_name='requiem',
            name='reqLevel',
        ),
        migrations.AddField(
            model_name='requiem',
            name='alt',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wowprof.alt'),
            preserve_default=False,
        ),
    ]
