# Generated by Django 3.1.7 on 2021-04-10 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0019_auto_20201120_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltMedia',
            fields=[
                ('alt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wowprof.alt')),
                ('altMediaExpiryDate', models.DateTimeField()),
                ('avatar', models.CharField(max_length=100)),
                ('inset', models.CharField(max_length=100)),
                ('main', models.CharField(max_length=100)),
                ('mainRaw', models.CharField(max_length=100)),
            ],
        ),
    ]
