# Generated by Django 3.1.7 on 2021-05-12 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0020_altmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltCustom',
            fields=[
                ('alt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wowprof.alt')),
                ('mount', models.CharField(choices=[('1 - Slow Ground', 'Slow Ground'), ('2 - Fast Ground', 'Fast Ground'), ('3 - Slow Flying', 'Slow Flying'), ('4 - Fast Flying', 'Fast Flying')], max_length=15)),
                ('garrison', models.CharField(choices=[('Level 0', 'Level0'), ('Level 1', 'Level1'), ('Level 2', 'Level2'), ('Level 3', 'Level3')], max_length=7)),
                ('mageTower', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('profession1', models.CharField(choices=[('None', 'None'), ('Alchemy', 'Alchemy'), ('Blacksmithing', 'Blacksmithing'), ('Enchanting', 'Enchanting'), ('Engineering', 'Engineering'), ('Inscription', 'Inscription'), ('Jewelcrafting', 'Jewelcrafting'), ('Leatherworking', 'Leatherworking'), ('Tailoring', 'Tailoring'), ('Herbalism', 'Herbalism'), ('Mining', 'Mining'), ('Skinning', 'Skinning')], max_length=14)),
                ('profession2', models.CharField(choices=[('None', 'None'), ('Alchemy', 'Alchemy'), ('Blacksmithing', 'Blacksmithing'), ('Enchanting', 'Enchanting'), ('Engineering', 'Engineering'), ('Inscription', 'Inscription'), ('Jewelcrafting', 'Jewelcrafting'), ('Leatherworking', 'Leatherworking'), ('Tailoring', 'Tailoring'), ('Herbalism', 'Herbalism'), ('Mining', 'Mining'), ('Skinning', 'Skinning')], max_length=14)),
            ],
        ),
    ]
