# Generated by Django 3.1.7 on 2021-05-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0022_altcustom_lastrefresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altcustom',
            name='profession1',
            field=models.CharField(choices=[('Missing', 'Missing'), ('Alchemy', 'Alchemy'), ('Blacksmithing', 'Blacksmithing'), ('Enchanting', 'Enchanting'), ('Engineering', 'Engineering'), ('Inscription', 'Inscription'), ('Jewelcrafting', 'Jewelcrafting'), ('Leatherworking', 'Leatherworking'), ('Tailoring', 'Tailoring'), ('Herbalism', 'Herbalism'), ('Mining', 'Mining'), ('Skinning', 'Skinning')], max_length=14),
        ),
        migrations.AlterField(
            model_name='altcustom',
            name='profession2',
            field=models.CharField(choices=[('Missing', 'Missing'), ('Alchemy', 'Alchemy'), ('Blacksmithing', 'Blacksmithing'), ('Enchanting', 'Enchanting'), ('Engineering', 'Engineering'), ('Inscription', 'Inscription'), ('Jewelcrafting', 'Jewelcrafting'), ('Leatherworking', 'Leatherworking'), ('Tailoring', 'Tailoring'), ('Herbalism', 'Herbalism'), ('Mining', 'Mining'), ('Skinning', 'Skinning')], max_length=14),
        ),
    ]
