# Generated by Django 3.1.7 on 2021-05-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0023_auto_20210512_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altcustom',
            name='garrison',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Built'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=0),
        ),
    ]
