# Generated by Django 3.1.7 on 2021-05-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0024_auto_20210512_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altcustom',
            name='mount',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Slow Ground'), (2, 'Fast Ground'), (3, 'Slow Flying'), (4, 'Fast Flying')], default=1),
        ),
    ]
