# Generated by Django 3.1.7 on 2021-05-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0027_auto_20210513_0023'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alt',
            table='alttracker_alt',
        ),
    ]
