# Generated by Django 3.1.7 on 2021-05-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0028_auto_20210513_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requiem',
            name='alt',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.AlterModelTable(
            name='altachievement',
            table='alttracker_altachievement',
        ),
        migrations.AlterModelTable(
            name='altcustom',
            table='alttracker_altcustom',
        ),
        migrations.AlterModelTable(
            name='altmedia',
            table='alttracker_altmedia',
        ),
        migrations.AlterModelTable(
            name='altprofession',
            table='alttracker_altprofession',
        ),
        migrations.AlterModelTable(
            name='altquestcompleted',
            table='alttracker_altquestcompleted',
        ),
        migrations.DeleteModel(
            name='Requiem',
        ),
    ]
