# Generated by Django 3.1.7 on 2021-05-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0030_auto_20210513_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alt',
            name='altClass',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Class'), (1, 'Warrior'), (2, 'Paladin'), (3, 'Hunter'), (4, 'Rogue'), (5, 'Priest'), (6, 'Death Knight'), (7, 'Shaman'), (8, 'Mage'), (9, 'Warlock'), (10, 'Monk'), (11, 'Druid'), (12, 'Demon Hunter')], default=0),
        ),
    ]
