# Generated by Django 3.1.7 on 2021-05-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0032_auto_20210513_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alt',
            name='altFaction',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Faction'), (1, 'Alliance'), (2, 'Horde')], default=0),
        ),
        migrations.AlterField(
            model_name='alt',
            name='altGender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Gender'), (1, 'Male'), (2, 'Female')], default=0),
        ),
    ]
