# Generated by Django 3.1.7 on 2021-05-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0033_auto_20210513_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altprofession',
            name='professionName',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Missing'), (1, 'Alchemy'), (2, 'Blacksmithing'), (3, 'Enchanting'), (4, 'Engineering'), (5, 'Inscription'), (6, 'Jewelcrafting'), (7, 'Leatherworking'), (8, 'Tailoring'), (9, 'Herbalism'), (10, 'Mining'), (11, 'Skinning')]),
        ),
    ]
