# Generated by Django 3.1.7 on 2021-05-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0041_auto_20210516_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
