# Generated by Django 3.1.7 on 2021-05-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0042_auto_20210517_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='altequipment',
            old_name='level',
            new_name='item_level',
        ),
        migrations.AddField(
            model_name='altequipment',
            name='slot',
            field=models.CharField(default='temptype', max_length=20),
            preserve_default=False,
        ),
    ]
