# Generated by Django 3.1.7 on 2021-05-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0043_auto_20210517_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='required_level',
            field=models.CharField(max_length=80),
        ),
    ]
