# Generated by Django 3.1.7 on 2021-05-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0044_auto_20210517_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='required_level',
        ),
    ]
