# Generated by Django 3.1.7 on 2021-05-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0045_remove_equipment_required_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='alt',
            name='altRealmSlug',
            field=models.CharField(default='tempslug', max_length=40),
            preserve_default=False,
        ),
    ]
