# Generated by Django 3.1.7 on 2021-05-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0047_auto_20210517_1714'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='altprofession',
            constraint=models.UniqueConstraint(fields=('alt', 'profession'), name='unique_profession'),
        ),
    ]
