# Generated by Django 3.1.7 on 2021-05-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0048_auto_20210517_1722'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='altprofession',
            unique_together=set(),
        ),
    ]
