# Generated by Django 3.1.7 on 2021-05-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0050_auto_20210517_1727'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alt',
            unique_together=set(),
        ),
    ]
