# Generated by Django 3.1.7 on 2021-05-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0054_altequipment_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='quality',
        ),
    ]
