# Generated by Django 3.1.7 on 2021-05-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0055_remove_equipment_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='altcustom',
            name='shadowmourne',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'N/A')], default=2),
        ),
    ]
