# Generated by Django 3.1.7 on 2021-05-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0056_altcustom_shadowmourne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altcustom',
            name='mageTower',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'N/A')], default=2),
        ),
    ]
