# Generated by Django 3.1.7 on 2021-05-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0057_auto_20210521_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='altcustom',
            name='balance_of_power',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
