# Generated by Django 3.1.7 on 2021-05-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0060_auto_20210521_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altcustom',
            name='balance_of_power',
        ),
        migrations.AlterField(
            model_name='altcustom',
            name='shadowmourne',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'N/A'), (3, 'Quest')], default=2),
        ),
    ]
