# Generated by Django 3.1.7 on 2021-05-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0061_auto_20210521_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='altequipment',
            name='spells',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
