# Generated by Django 3.1.7 on 2021-05-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0062_altequipment_spells'),
    ]

    operations = [
        migrations.AddField(
            model_name='altequipment',
            name='azerite',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
