# Generated by Django 3.1.7 on 2021-05-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0063_altequipment_azerite'),
    ]

    operations = [
        migrations.AddField(
            model_name='altcustom',
            name='average_item_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
