# Generated by Django 3.1.7 on 2021-06-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0064_altcustom_average_item_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='alt',
            name='altRealmId',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
