# Generated by Django 3.1.7 on 2021-06-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowprof', '0067_auto_20210610_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altcustom',
            name='gold',
            field=models.CharField(max_length=12),
        ),
    ]
